[package]
name = "pyrustbio"
version = "0.1.0"
authors = ["jeff-k <jeff@x-0.ca>"]

[lib]
name = "pyrustbio"
crate-type = ["cdylib"]

[dependencies]
bio = "*"

[dependencies.pyo3]
git = "https://github.com/PyO3/pyo3.git"
features = ["extension-module"]
