[package]
name = "pyrustbio"
version = "0.2.0"
authors = ["jeff-k <jeff@x-0.ca>"]
edition = "2018"

[lib]
name = "pyrustbio"
crate-type = ["cdylib"]

[dependencies]
bio = "0.34.0"
pyo3 = { version = "0.13.2", features = ["extension-module"] }
