[package]
name = "pyrustbio"
version = "0.1.0"
authors = ["jeff-k <jeff@x-0.ca>"]
edition = "2018"

[lib]
name = "pyrustbio"
crate-type = ["cdylib"]

[dependencies]
bio = "*"

[dependencies.pyo3]
features = ["extension-module"]
